[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
no_match_coverage = "^(test|script)/"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
